import Link from "next/link";
import { DrawdownChart, EquityCurve } from "@/components/charts";
import { DataModeBadge } from "@/components/data-mode-badge";
import { ResearchDisclaimer } from "@/components/disclaimer";
import { StrategyExport } from "@/components/strategy-export";
import { StrategyHash } from "@/components/strategy-hash";
import { Badge, Button, Card, CardContent, CardDescription, CardHeader, CardTitle, SectionHeader } from "@/components/ui";
import { getMarketData, getMarketFromList } from "@/lib/data-mode";
import { createStrategySignalSnapshot, generateBacktest, getStrategyById, type StrategySignalSnapshot } from "@/lib/market-data";
import { formatCompactNumber, formatCurrency, formatPercent, signedToneClass } from "@/lib/utils";

export const dynamic = "force-dynamic";

export default async function StrategyDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const resolvedParams = await params;
  const marketData = await getMarketData();
  const strategy = getStrategyById(resolvedParams.id, marketData.markets);
  const market = getMarketFromList(marketData.markets, strategy.symbol);
  const backtest = generateBacktest(strategy);
  const snapshot = createStrategySignalSnapshot({ market, strategy, backtest });

  return (
    <div className="space-y-8">
      <SectionHeader
        eyebrow="Final strategy artifact"
        title="Backtestable Strategy Spec"
        description="This is the backtestable strategy spec generated by the SignalPilot Market Intelligence Skill."
      />
      <div className="flex flex-wrap items-center gap-2">
        <DataModeBadge status={marketData.status} />
        <Badge variant="outline">Strategy Intelligence Spec</Badge>
      </div>
      <ResearchDisclaimer />
      <StrategyHash snapshot={snapshot} />

      <Card className="border-cyan-300/20 bg-cyan-300/10 p-5">
        <div className="grid gap-4 lg:grid-cols-[1fr_auto] lg:items-center">
          <div>
            <p className="text-xs font-semibold uppercase tracking-[0.18em] text-cyan-200">
              Judge deliverable
            </p>
            <h2 className="mt-2 text-2xl font-semibold text-slate-100">{strategy.name}</h2>
            <p className="mt-2 max-w-3xl text-sm leading-6 text-cyan-100/80">
              The JSON below is the central SignalPilot artifact: skill name, track name, selected market, CMC signal snapshot, derived indicators, strategy rules, risk rules, backtest assumptions, backtest metrics, AI reasoning, and deterministic strategy hash.
            </p>
          </div>
          <Badge variant="outline" className="border-cyan-300/30 bg-slate-950/60 text-cyan-100">
            Market Intelligence Skill output
          </Badge>
        </div>
      </Card>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Metric label="Market selected" value={strategy.symbol} />
        <Metric label="Type" value={strategy.type} />
        <Metric label="Confidence" value={`${strategy.confidenceScore}/100`} />
        <Metric label="Return" value={formatPercent(backtest.totalReturn)} tone={signedToneClass(backtest.totalReturn)} />
      </div>

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <Metric label="Sharpe ratio" value={backtest.sharpeRatio.toString()} />
        <Metric label="Max drawdown" value={formatPercent(backtest.maxDrawdown)} tone={signedToneClass(backtest.maxDrawdown)} />
        <Metric label="Win rate" value={formatPercent(backtest.winRate)} tone="text-emerald-300" />
        <Metric label="Profit factor" value={backtest.profitFactor.toString()} />
      </div>

      <div className="grid gap-4 lg:grid-cols-[0.95fr_1.05fr]">
        <Card className="p-5">
          <div className="flex items-center justify-between gap-4">
            <h2 className="font-semibold">CMC quote fields and derived indicators used</h2>
            <Badge variant="outline">Market regime: {market.marketRegime}</Badge>
          </div>
          <div className="mt-5 grid gap-3 sm:grid-cols-2">
            <Metric label="Live CMC price" value={formatCurrency(market.price)} />
            <Metric label="Live CMC 24h price" value={formatPercent(market.priceChange24h)} tone={signedToneClass(market.priceChange24h)} />
            <Metric label="Live CMC 24h volume" value={formatCompactNumber(market.volume24h)} />
            <Metric label="Live CMC volume change" value={formatPercent(market.volumeChange24h)} tone={signedToneClass(market.volumeChange24h)} />
            <Metric label="Live CMC market cap" value={formatCompactNumber(market.marketCap)} />
            <Metric label="Derived RSI" value={market.rsi.toString()} />
            <Metric label="Derived MACD" value={market.macdSignal} />
            <Metric label="Derived EMA" value={market.emaTrend} />
            <Metric label="Derived volatility" value={market.volatilityScore.toString()} />
            <Metric label="Derived sentiment" value={market.sentimentScore.toString()} />
            <Metric label="Derived narrative" value={market.narrativeMomentum.toString()} />
            <Metric label="Optional derivatives placeholder" value={market.openInterestFunding} />
            <Metric label="Data source" value={market.dataSource ?? "unknown"} />
            <Metric label="Last updated" value={market.lastUpdated ? new Date(market.lastUpdated).toLocaleString() : "Mock snapshot"} />
          </div>
        </Card>

        <Card className="p-5">
          <h2 className="font-semibold">Strategy logic</h2>
          <div className="mt-5 grid gap-5 md:grid-cols-2">
            <List title="Entry rules" items={strategy.entryConditions} />
            <List title="Exit rules" items={strategy.exitConditions} />
            <List title="Risk rules" items={strategy.riskRules} />
            <List title="CMC quote fields and derived indicators used" items={strategy.signalsUsed} />
          </div>
          <div className="mt-5 rounded-lg border border-border bg-slate-950/45 p-4">
            <p className="text-xs font-semibold uppercase tracking-[0.16em] text-accent">AI reasoning</p>
            <p className="mt-2 text-sm leading-6 text-muted-foreground">{strategy.reasoning}</p>
          </div>
        </Card>
      </div>

      <div className="grid gap-4 lg:grid-cols-2">
        <Card className="p-5">
          <h2 className="font-semibold">Backtest equity</h2>
          <EquityCurve data={backtest.equityCurve} />
        </Card>
        <Card className="p-5">
          <h2 className="font-semibold">Backtest drawdown</h2>
          <DrawdownChart data={backtest.drawdownCurve} />
        </Card>
      </div>

      <SnapshotPanel snapshot={snapshot} />

      <Card className="p-5">
        <h2 className="font-semibold">Complete JSON strategy spec</h2>
        <p className="mt-1 text-sm leading-6 text-muted-foreground">
          Copy or download the complete backtestable strategy spec for audit, handoff, strategy verification, or future proof registration. This export contains the SignalPilot Market Intelligence Skill output and includes the deterministic strategy hash.
        </p>
        <div className="mt-4">
          <StrategyExport snapshot={snapshot} />
        </div>
      </Card>

      <Card className="grid gap-4 p-5 md:grid-cols-[1fr_auto] md:items-center">
        <div>
          <h2 className="font-semibold">Next step: proof registry placeholder</h2>
          <p className="mt-1 text-sm leading-6 text-muted-foreground">
            See how SignalPilot could later anchor this deterministic strategy hash and backtest score to BNB Chain.
          </p>
        </div>
        <Link href="/proof">
          <Button variant="secondary">View Mock Proof</Button>
        </Link>
      </Card>
    </div>
  );
}

function SnapshotPanel({ snapshot }: { snapshot: StrategySignalSnapshot }) {
  return (
    <Card className="overflow-hidden">
      <CardHeader className="border-b border-border">
        <CardTitle>Complete signal snapshot</CardTitle>
        <CardDescription>
          The exact market context, Live CMC Data quote fields, derived indicators, rules, and backtest metrics preserved for this generated strategy.
        </CardDescription>
      </CardHeader>
      <CardContent className="grid gap-5 pt-5 lg:grid-cols-3">
        <div className="space-y-3">
          <h3 className="text-sm font-semibold">Generation context</h3>
          <Metric label="Selected market" value={snapshot.selectedMarket} />
          <Metric label="Skill name" value={snapshot.skillName} />
          <Metric label="Platform" value={snapshot.trackName} />
          <Metric label="Timestamp" value={new Date(snapshot.timestamp).toLocaleString()} />
          <Metric label="Source" value={snapshot.source} />
          <Metric label="Data source" value={snapshot.dataSource} />
          <Metric label="Market regime" value={snapshot.marketRegime} />
        </div>
        <div className="space-y-3">
          <h3 className="text-sm font-semibold">Live CMC Data quote fields</h3>
          <Metric label="Price" value={formatCurrency(snapshot.rawLiveMarketValues.price)} />
          <Metric label="24h price" value={formatPercent(snapshot.rawLiveMarketValues.priceChange24h)} tone={signedToneClass(snapshot.rawLiveMarketValues.priceChange24h)} />
          <Metric label="24h volume" value={formatCompactNumber(snapshot.rawLiveMarketValues.volume24h)} />
          <Metric label="Market cap" value={formatCompactNumber(snapshot.rawLiveMarketValues.marketCap)} />
        </div>
        <div className="space-y-3">
          <h3 className="text-sm font-semibold">Derived indicators and results</h3>
          <Metric label="Derived RSI / MACD" value={`${snapshot.indicatorsUsed.rsi} / ${snapshot.indicatorsUsed.macdSignal}`} />
          <Metric label="Derived EMA trend" value={snapshot.indicatorsUsed.emaTrend} />
          <Metric label="Derived support" value={snapshot.indicatorsUsed.support.join(" / ")} />
          <Metric label="Derived resistance" value={snapshot.indicatorsUsed.resistance.join(" / ")} />
          <Metric label="Backtest return" value={formatPercent(snapshot.backtestMetrics.totalReturn)} tone={signedToneClass(snapshot.backtestMetrics.totalReturn)} />
          <Metric label="Max drawdown" value={formatPercent(snapshot.backtestMetrics.maxDrawdown)} tone={signedToneClass(snapshot.backtestMetrics.maxDrawdown)} />
        </div>
      </CardContent>
    </Card>
  );
}

function Metric({ label, value, tone }: { label: string; value: string; tone?: string }) {
  return (
    <div className="rounded-lg border border-border bg-slate-950/45 p-4">
      <p className="text-xs font-semibold uppercase tracking-[0.16em] text-muted-foreground">{label}</p>
      <p className={`mt-2 text-sm font-semibold ${tone ?? ""}`}>{value}</p>
    </div>
  );
}

function List({ title, items }: { title: string; items: string[] }) {
  return (
    <div>
      <h3 className="text-sm font-semibold">{title}</h3>
      <ul className="mt-3 space-y-2 text-sm leading-6 text-muted-foreground">
        {items.map((item) => (
          <li key={item} className="rounded-md border border-border bg-slate-950/45 px-3 py-2">{item}</li>
        ))}
      </ul>
    </div>
  );
}
